import './globals.css';

import type { Metadata } from 'next';

import ApolloProviderWrapper from '@/providers/ApolloProviderWrapper';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Vertuoza Test by Younce',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ApolloProviderWrapper>
          {children}
          <Toaster />
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
