import './globals.css';

import type { Metadata } from 'next';

import ApolloProviderWrapper from '@/providers/ApolloProviderWrapper';

export const metadata: Metadata = {
  title: 'Vertuoza test by Younce',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <ApolloProviderWrapper>
        <body
          className={'antialiased'}
        >
          {children}
        </body>
      </ApolloProviderWrapper>
    </html>
  );
}
